config/routes.rb
Ticketee::Application.routes.draw do
  get 'admin/users' => 'admin/users#index'
  devise_for :users
  root to: "projects#index"
  resources :projects do
    resources :tickets
  end

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Project < ActiveRecord::Base
	has_many :tickets, dependent: :delete_all
	validates :name, presence: true
end

app/models/ticket.rb
# == Schema Information
#
# Table name: tickets
#
#  id          :integer          not null, primary key
#  title       :string(255)
#  description :text
#  project_id  :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Ticket < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  validates :title, presence: true 
  validates :description, presence: true, length: { minimum: 10 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  unconfirmed_email      :string(255)
#  confirmation_sent_at   :datetime
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
	before_filter :authorize_admin!
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

		def authorize_admin!
			authenticate_user!
			unless current_user.admin?
				flash[:alert] = "You must be an admin to do that."
				redirect_to root_path
			end
		end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_filter :authorize_admin!, except: [:index, :show]
	before_filter :find_project, only: [:show, :edit, :update, :destroy]

	def index
		@projects = Project.all
	end

	def new
		@project = Project.new
	end

	def create
		@project = Project.new(project_params)
		if @project.save
			flash[:notice] = "Project has been created."
			redirect_to @project
		else
			flash[:alert] = "Project has not been created."
			render action: "new"
		end
	end

	def update
		if @project.update_attributes(project_params)
			flash[:notice] = "Project has been updated."
			redirect_to @project
		else
			flash[:alert] = "Project has not been updated."
			render action: "edit"
		end
	end

	def destroy
		@project.destroy
		flash[:notice] = "Project has been deleted."
		redirect_to projects_path
	end

	private

		def find_project
			@project = Project.find(params[:id])
			rescue ActiveRecord::RecordNotFound
				flash[:alert] = "The project you were looking for could not be found."
				redirect_to projects_path
		end

		def project_params
			params.require(:project).permit(:name, :description)
		end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
	before_filter :authenticate_user!, except: [:index, :show]
	before_filter :find_project
	before_filter :find_ticket, only: [:show, :edit, :update, :destroy]

	def show
	end

	def new
		@ticket = @project.tickets.build
	end

	def create
		@ticket = @project.tickets.build(ticket_params)
		@ticket.user = current_user
		if @ticket.save
			flash[:notice] = "Ticket has been created."
			redirect_to	[@project, @ticket]
		else
			flash[:alert] = "Ticket has not been created."
			render action: "new"
		end
	end

	def edit	
	end

	def update
		if @ticket.update_attributes(ticket_params)
			flash[:notice] = "Ticket has been updated."
			redirect_to [@project, @ticket]
		else
			flash[:alert] = "Ticket has not been updated."
			render action: "edit"
		end
	end

	def destroy
		@ticket.destroy
		flash[:notice] = "Ticket has been deleted."
		redirect_to @project
	end

	private
		def find_project
			@project = Project.find(params[:project_id])
		end

		def find_ticket
			@ticket = @project.tickets.find(params[:id])
		end

		def ticket_params
			params.require(:ticket).permit(:title, :description)
		end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(*parts)
		unless parts.empty?
			content_for :title do
				(parts << "Ticketee").join(" - ")
			end
		end
	end

	def admins_only(&block)
		concat(block.call) if current_user.try(:admin?)
	end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/admin/users/index.html.erb
<h1>Admin::Users#index</h1>
<p>Find me in app/views/admin/users/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
  	<% if content_for?(:title) %>
  		<%= yield(:title) %>
  	<% else %>
  		Ticketee
  	<% end %>
  </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
	<div class='flash' id='<%= key %>'>
		<%= value %>
	</div>
<% end %>

<% if user_signed_in? %>
  Signed in as <%= current_user.email %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path %>
  <%= link_to "Sign in", new_user_session_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
	<% if @project.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@project.errors.count, "error") %>
				prohibited this foo from being saved:</h2>
			<ul>
			<% @project.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :description %><br />
		<%= f.text_field :description %>
	</p>
	<%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>
<%= render "form" %>

app/views/projects/index.html.erb
<h2>Projects</h2>
<ul>
	<% @projects.each do |project| %>
		<li><%= link_to project.name, project %></li>
	<% end %>
</ul>
<% admins_only do %>
	<%= link_to "New Project", new_project_path %>
<% end %>

app/views/projects/new.html.erb
<h2>New Project</h2>
<%= render "form" %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<h2><%= @project.name %></h2>

<% admins_only do %>
	<%= link_to "Edit Project", edit_project_path(@project) %>
	<%= link_to "Delete Project",
			project_path(@project), method: :delete,
			data: { confirm: "Are you sure you want to delete this project?" } %>
<% end %>
<%= link_to "New Ticket", new_project_ticket_path(@project) %>

<ul id='tickets'>
	<% @project.tickets.each do |ticket| %>
		<li>
			#<%= ticket.id %> -
			<%= link_to ticket.title, [@project, ticket] %>
		</li>
	<% end %>
</ul>

app/views/tickets/_form.html.erb
<%= form_for [@project, @ticket] do |f| %>
	<% if @ticket.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@ticket.errors.count, "error") %>
				prohibited this foo from being saved:</h2>
			<ul>
			<% @ticket.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :description %><br>
		<%= f.text_area :description %>
	</p>
	<%= f.submit %>
<% end %>

app/views/tickets/edit.html.erb
<h2>Editing a ticket in <%= @project.name %></h2>
<%= render "form" %>

app/views/tickets/new.html.erb
<h2>New Ticket</h2>
<%= render "form" %>

app/views/tickets/show.html.erb
<div id='ticket'>
	<h2><%= @ticket.title %></h2>
	<span id='author'>Created by <%= @ticket.user.email %></span>
	<%= link_to "Edit Ticket", [:edit, @project, @ticket] %>
	<%= link_to "Delete Ticket", [@project, @ticket], method: :delete,
						data: { confirm: "Are you sure you want to delete this ticket?" } %>
	<%= simple_format(@ticket.description) %>
</div>